[workspace.package]
version = "0.1.13"
edition = "2024"
repository = "https://github.com/XiangpengHao/liquid-cache"
authors = ["XiangpengHao <xiangpeng.hao@wisc.edu>"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "10x lower latency for cloud-native DataFusion"


[workspace]
members = [
	"benchmark",
	"src/datafusion-server",
	"src/datafusion-client",
	"src/datafusion",
	"src/common",
	"src/core",
	"src/datafusion-local",
	"examples",
	"fuzz",
	"dev/dev-tools",
]
resolver = "3"

[workspace.dependencies]
liquid-cache-datafusion-server = { path = "src/datafusion-server", version = "0.1.13" }
liquid-cache-datafusion-client = { path = "src/datafusion-client", version = "0.1.13" }
liquid-cache-datafusion = { path = "src/datafusion", version = "0.1.13" }
liquid-cache-common = { path = "src/common", version = "0.1.13" }
liquid-cache = { path = "src/core", version = "0.1.13" }
liquid-cache-datafusion-local = { path = "src/datafusion-local", version = "0.1.13" }
arrow = { version = "59.2", default-features = false, features = [
	"prettyprint",
	"ipc",
] }
arrow-flight = { version = "59.2", features = ["flight-sql-experimental"] }
arrow-schema = { version = "59.2", features = ["serde"] }
parquet = { version = "59.2", features = [
	"async",
	"experimental",
	"variant_experimental",
] }
parquet-variant-json = { version = "59.2" }
parquet-variant-compute = { version = "59.2" }
datafusion = { version = "55" }
datafusion-common = { version = "55" }
datafusion-expr-common = { version = "55" }
datafusion-physical-expr = { version = "55" }
datafusion-physical-expr-common = { version = "55" }
datafusion-proto = { version = "55" }
async-trait = "0.1.89"
futures = { version = "0.3.32", default-features = false, features = ["std"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
log = "0.4.32"
tonic = { version = "0.14.6" }
url = "2.5.8"
bytes = { version = "1.11.1", default-features = false }
ahash = "0.8.12"
prost = "0.14.4"
object_store = { version = "0.13.2", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
tempfile = "3.27.0"
uuid = { version = "1.23.3", features = ["v4"] }
fastrace = "0.7"
fastrace-tonic = "0.2"
congee = "0.4.1"
insta = "1.47.2"
t4 = "0.1.7"

[profile.dev.package]
insta.opt-level = 3
