[package]
name = "liquid-cache-fuzz"
version = "0.1.13"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.4", features = ["derive"] }
arrow = { workspace = true }
liquid-cache = { workspace = true }
bytes = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr-common = { workspace = true }
datafusion-physical-expr = { workspace = true }

[[bin]]
name = "liquid_array"
path = "fuzz_targets/liquid_array.rs"
test = false
doc = false
bench = false
