[package]
name = "liquid-cache"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = { workspace = true }
repository = { workspace = true }

[dependencies]
async-stream = "0.3.6"
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
liquid-cache-common = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr-common = { workspace = true }
datafusion-physical-expr = { workspace = true }
arrow = { workspace = true }
arrow-schema = { workspace = true }
ahash = { workspace = true }
tempfile = { workspace = true }
congee = { workspace = true }
t4 = { workspace = true }
log = { workspace = true }
parquet = { workspace = true }
fastrace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
vortex-array = { workspace = true }
vortex-arrow = { workspace = true }
vortex-btrblocks = { workspace = true }
vortex-ipc = { workspace = true }
vortex-buffer = { workspace = true }
vortex-mask = { workspace = true }
vortex-session = { workspace = true }
vortex-error = { workspace = true }
vortex-fastlanes = { workspace = true }
vortex-fsst = { workspace = true }
vortex-alp = { workspace = true }
vortex-runend = { workspace = true }
vortex-sparse = { workspace = true }
vortex-zigzag = { workspace = true }
vortex-datetime-parts = { workspace = true }
vortex-decimal-byte-parts = { workspace = true }
vortex-bytebool = { workspace = true }
vortex-sequence = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
shuttle = "0.9.1"
tokio-test = "0.4"
tracing-subscriber = "0.3.23"
serde.workspace = true
serde_json = { workspace = true }
mimalloc = "0.1.52"
clap = { version = "4.6.1", features = ["derive"] }
insta = { workspace = true }
datafusion = { workspace = true }

[features]
shuttle = ["t4/shuttle"]

[[bench]]
name = "cache_storage"
path = "study/cache_storage.rs"
harness = false
