[package]
name = "liquid-cache"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = { workspace = true }
repository = { workspace = true }

[dependencies]
async-stream = "0.3.6"
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
liquid-cache-common = { workspace = true }
datafusion-common = { workspace = true }
datafusion-expr-common = { workspace = true }
datafusion-physical-expr = { workspace = true }
datafusion-physical-expr-common = { workspace = true }
arrow = { workspace = true }
arrow-schema = { workspace = true }
fastlanes = "0.7.0"
num-traits = "0.2.19"
fsst-rs = "0.6.0"
ahash = { workspace = true }
tempfile = { workspace = true }
congee = { workspace = true }
t4 = { workspace = true }
log = { workspace = true }
parquet = { workspace = true }
parquet-variant-compute = { workspace = true }
fastrace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }

[dev-dependencies]
tempfile = { workspace = true }
shuttle = "0.9.1"
tokio-test = "0.4"
tracing-subscriber = "0.3.23"
rand = "0.10.1"
serde.workspace = true
serde_json = { workspace = true }
mimalloc = "0.1.52"
clap = { version = "4.6.1", features = ["derive"] }
divan = "0.1.21"
insta = { workspace = true }
datafusion = { workspace = true }

[features]
shuttle = ["t4/shuttle"]

[[bench]]
name = "fsst_view_study"
path = "study/fsst_view.rs"
harness = false

[[bench]]
name = "fsst_selectivity"
path = "study/fsst_selectivity.rs"
harness = false

[[bench]]
name = "fsstarray"
path = "bench/fsstarray.rs"
harness = false

[[bench]]
name = "byte_view_compare"
path = "bench/byte_view_compare.rs"
harness = false

[[bench]]
name = "bitpacking"
path = "bench/bitpacking.rs"
harness = false

[[bench]]
name = "liquid_float_array"
harness = false
path = "bench/liquid_float_array.rs"

[[bench]]
name = "cache_storage"
path = "study/cache_storage.rs"
harness = false

[[bench]]
name = "linear_integer_study"
path = "study/linear_integer.rs"
harness = false

[[bench]]
name = "squeeze_integer_study"
path = "study/squeeze_integer.rs"
harness = false

[[bench]]
name = "squeeze_date32"
path = "bench/squeeze_date32.rs"
harness = false

[[bench]]
name = "primitive_encoding"
path = "bench/primitive_encoding.rs"
harness = false

[[bench]]
name = "string_fingerprint_study"
path = "study/string-fingerprint.rs"
harness = false

[[bench]]
name = "filter_selectivity_ambiguity"
path = "study/filter_selectivity_ambiguity.rs"
harness = false

[[bench]]
name = "prefix_differentiability"
path = "study/prefix_differentiability.rs"
harness = false
