name: Rust CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Format, clippy and compile check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy, rustfmt
            - uses: Swatinem/rust-cache@v2

            - name: Check formatting
              run: cargo fmt --all -- --check

            - name: Run clippy
              run: cargo clippy --workspace --exclude dev-tools --all-targets --all-features -- -D warnings -A clippy::uninlined-format-args -A clippy::useless-conversion

            - name: Run tests
              run: cargo test --workspace --exclude dev-tools
